intro_text = ''' In this world health realted objects are alive their health protected by the great medicinic sphere however sugar cube the ex friend of the health guardian the protector of the medicinic sphere seeking revenge on his former friend destroyed the medicinic sphere leaving the world in ruins now it is up to the health guardians two brothers heart and broccoli to save the medicinic sphere by travelling through the land of ronosense all the way to the great land of kragonstan to retrieve a artifact that will restore the medicinic sphere find out the full story in the cutscenes or if your boring skip them and head to the gameplay click here to start
'''

instructions_text = ''' Space bar to jump right and left arrow key's to move left and right use the physics to your advantage by making good jumps from platform to platfrom and using level gimmicks to your advantage for example use the pink marshmallow in this level to bounce there are enemies in this level shoot them ratchet and clank style with the worst weapon broccoli broccoli will throw parts of himself into there mouths and make them see just how terrible it is to eat broccoli
'''

intro_text_prophecy = ''' In a story set far before the events of the apocalyptic junk day that will destroy the entire world Applecartis the creator of the medicinic sphere meant to protect all living things has put a vision inside of the dream of the chosen one he knows is destined to be the one true protector of the medicinic sphere the health gaurdian this vision put by him will decide the fate of the entire world
'''
instructions_text_prophecy = ''' Space bar to jump right and left arrow key's to move left and right use the physics to your advantage by making good jumps from platform to platfrom and using level gimmicks to your advantage for example use the pink marshmallow in this level to bounce from platform to platform or use the wider marshmallow platforms for a bigger run before you jump or to have more room to bounce on the platform if it's a pink one well that's all enjoy
'''